
spring:
  application:
    name: movement-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8083/.well-known/jwks.json
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 52MB

server:
  port: 8084
  error:
    include-message: always
    include-binding-errors: always

# Audit logging
audit:
  service:
    url: http://localhost:8083
