
spring:
  application:
    name: inventory-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8083/.well-known/jwks.json
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 52MB
  datasource:
    url: jdbc:postgresql://localhost:5433/inventory_db
    username: inventory_user
    password: inventory_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 8086
  error:
    include-message: always
    include-binding-errors: always

# Audit logging
audit:
  service:
    url: http://localhost:8083
