import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { saveAs } from 'file-saver';
import { format } from 'date-fns';

export type ReportFormat = 'excel' | 'pdf' | 'csv';

export interface ReportColumn {
  header: string;
  key: string;
  width?: number;
}

export interface ReportConfig {
  title: string;
  subtitle?: string;
  columns: ReportColumn[];
  data: Record<string, unknown>[];
  filename?: string;
  generatedBy?: string;
}

// ─── EXCEL REPORT ────────────────────────────────────────────────────────────

export function generateExcelReport(config: ReportConfig): void {
  const { title, columns, data, filename = 'report' } = config;

  // Create workbook and worksheet
  const wb = XLSX.utils.book_new();

  // Header row
  const headerRow = columns.map(c => c.header);

  // Data rows
  const dataRows = data.map(row =>
    columns.map(col => {
      const value = row[col.key];
      if (value === null || value === undefined) return '';
      if (value instanceof Date) return format(value, 'yyyy-MM-dd HH:mm');
      return String(value);
    })
  );

  // Combine header + data
  const wsData = [headerRow, ...dataRows];
  const ws = XLSX.utils.aoa_to_sheet(wsData);

  // Column widths
  ws['!cols'] = columns.map(col => ({ wch: col.width || Math.max(col.header.length + 4, 15) }));

  // Style header row (bold, background)
  const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');
  for (let C = range.s.c; C <= range.e.c; ++C) {
    const cellAddr = XLSX.utils.encode_cell({ r: 0, c: C });
    if (!ws[cellAddr]) continue;
    ws[cellAddr].s = {
      font: { bold: true, color: { rgb: 'FFFFFF' } },
      fill: { fgColor: { rgb: '1D4ED8' } },
      alignment: { horizontal: 'center' },
    };
  }

  XLSX.utils.book_append_sheet(wb, ws, title.substring(0, 31));

  // Add metadata sheet
  const metaData = [
    ['Report Title', title],
    ['Generated At', format(new Date(), 'yyyy-MM-dd HH:mm:ss')],
    ['Total Records', data.length.toString()],
    ['Generated By', config.generatedBy || 'Stock Management System'],
  ];
  const metaWs = XLSX.utils.aoa_to_sheet(metaData);
  metaWs['!cols'] = [{ wch: 20 }, { wch: 40 }];
  XLSX.utils.book_append_sheet(wb, metaWs, 'Report Info');

  // Save file
  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([excelBuffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  });
  const dateStr = format(new Date(), 'yyyy-MM-dd');
  saveAs(blob, `${filename}-${dateStr}.xlsx`);
}

// ─── PDF REPORT ───────────────────────────────────────────────────────────────

export function generatePdfReport(config: ReportConfig): void {
  const { title, subtitle, columns, data, filename = 'report' } = config;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();

  // ─ Header Background
  doc.setFillColor(29, 78, 216); // Blue #1D4ED8
  doc.rect(0, 0, pageWidth, 35, 'F');

  // ─ Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text(title, 14, 16);

  // ─ Subtitle/Date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(200, 210, 255);
  const dateStr = format(new Date(), 'PPP');
  doc.text(subtitle || `Generated on ${dateStr}`, 14, 26);

  // ─ Record count (right aligned)
  doc.setTextColor(200, 210, 255);
  const recordText = `${data.length} record${data.length !== 1 ? 's' : ''}`;
  doc.text(recordText, pageWidth - 14, 16, { align: 'right' });

  // ─ Table
  const tableColumns = columns.map(col => ({
    header: col.header,
    dataKey: col.key,
  }));

  const tableData = data.map(row =>
    Object.fromEntries(
      columns.map(col => {
        const value = row[col.key];
        if (value === null || value === undefined) return [col.key, ''];
        if (value instanceof Date) return [col.key, format(value, 'yyyy-MM-dd')];
        return [col.key, String(value)];
      })
    )
  );

  autoTable(doc, {
    startY: 42,
    columns: tableColumns,
    body: tableData,
    styles: {
      fontSize: 8,
      cellPadding: 3,
      overflow: 'linebreak',
    },
    headStyles: {
      fillColor: [29, 78, 216],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [240, 245, 255],
    },
    bodyStyles: {
      textColor: [30, 30, 30],
    },
    columnStyles: Object.fromEntries(
      columns.map((col, idx) => [idx, { cellWidth: col.width || 'auto' }])
    ),
    didDrawPage: (hookData) => {
      // Footer on each page
      const pageCount = doc.getNumberOfPages();
      const currentPage = hookData.pageNumber;
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Page ${currentPage} of ${pageCount} — Stock Management System`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 8,
        { align: 'center' }
      );
    },
  });

  const dateFilename = format(new Date(), 'yyyy-MM-dd');
  doc.save(`${filename}-${dateFilename}.pdf`);
}

// ─── CSV CLIENT-SIDE EXPORT ───────────────────────────────────────────────────

export function generateCsvReport(config: ReportConfig): void {
  const { columns, data, filename = 'report' } = config;

  const headerRow = columns.map(c => `"${c.header}"`).join(',');
  const dataRows = data.map(row =>
    columns.map(col => {
      const value = row[col.key];
      if (value === null || value === undefined) return '';
      const str = String(value).replace(/"/g, '""');
      return `"${str}"`;
    }).join(',')
  );

  const csvContent = '\uFEFF' + [headerRow, ...dataRows].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const dateStr = format(new Date(), 'yyyy-MM-dd');
  saveAs(blob, `${filename}-${dateStr}.csv`);
}
