spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres-sales:5432/sales_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    open-in-view: false

server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always

audit:
  service:
    url: http://auth-service:8083

services:
  inventory-service:
    url: http://inventory-service:8086

logging:
  level:
    com.stock.salesservice: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}
      environment: docker
