spring:
  application:
    name: location-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8083/.well-known/jwks.json
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5435/location_db
    username: location_user
    password: location_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always

# Audit logging
audit:
  service:
    url: http://localhost:8083
